project_id = "zprkdxmluvirxfhswrzq"

[functions.send-notification]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.seal-invoice-verifactu]
verify_jwt = true

[functions.sign-invoice-verifactu]
verify_jwt = true

[functions.cancel-registro-facturacion]
verify_jwt = true
