-- Add new columns to assessment_templates for flexible response scales
ALTER TABLE public.assessment_templates 
ADD COLUMN IF NOT EXISTS response_min INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS response_max INTEGER NOT NULL DEFAULT 7,
ADD COLUMN IF NOT EXISTS chart_full_mark NUMERIC NOT NULL DEFAULT 7,
ADD COLUMN IF NOT EXISTS flag_threshold NUMERIC NOT NULL DEFAULT 4,
ADD COLUMN IF NOT EXISTS min_label TEXT,
ADD COLUMN IF NOT EXISTS max_label TEXT;

-- Update existing SELFCARE template to have explicit values
UPDATE public.assessment_templates 
SET response_min = 1, response_max = 7, chart_full_mark = 7, flag_threshold = 4, min_label = 'Nada de acuerdo', max_label = 'Totalmente de acuerdo'
WHERE code = 'SELFCARE_V1';

-- Insert SCL-90-R template
INSERT INTO public.assessment_templates (
  center_id,
  code,
  name,
  description,
  version,
  response_min,
  response_max,
  chart_full_mark,
  flag_threshold,
  min_label,
  max_label,
  instructions,
  items,
  scoring,
  is_active
)
SELECT 
  center_id,
  'SCL90_V1',
  'SCL-90-R',
  'Symptom Checklist 90 Revised - Cuestionario de 90 síntomas (escala 0–4)',
  1,
  0,
  4,
  4,
  2,
  'Nada',
  'Extremo',
  'A continuación se presenta una lista de problemas y molestias que a veces tiene la gente. Por favor, lea cada uno de ellos cuidadosamente y seleccione el número que mejor describa CUÁNTO LE HA MOLESTADO O ANGUSTIADO ESE PROBLEMA DURANTE LA ÚLTIMA SEMANA, INCLUIDO EL DÍA DE HOY.',
  '[
    {"index":1,"text":"DOLOR DE CABEZA"},
    {"index":2,"text":"NERVIOSISMO O AGITACIÓN"},
    {"index":3,"text":"PENSAMIENTOS, PALABRAS, IDEAS NO DESEADAS QUE NO SE VAN DE LA MENTE"},
    {"index":4,"text":"SENSACIÓN DE DESMAYO O MAREO"},
    {"index":5,"text":"PÉRDIDA DEL DESEO O DEL PLACER SEXUAL"},
    {"index":6,"text":"JUZGAR A OTROS NEGATIVA O CRÍTICAMENTE"},
    {"index":7,"text":"LA IDEA DE QUE OTRA PERSONA PUEDA CONTROLAR SUS PENSAMIENTOS"},
    {"index":8,"text":"LA IMPRESIÓN DE QUE LA MAYORÍA DE SUS PROBLEMAS SON CULPA DE LOS DEMÁS"},
    {"index":9,"text":"DIFICULTAD PARA RECORDAR LAS COSAS"},
    {"index":10,"text":"PREOCUPARSE DEMASIADO POR LAS COSAS"},
    {"index":11,"text":"SENTIRSE ENOJADO O IRRITABLE"},
    {"index":12,"text":"DOLORES EN EL PECHO"},
    {"index":13,"text":"MIEDO A ESPACIOS ABIERTOS O CALLES"},
    {"index":14,"text":"SENTIR POCA ENERGÍA O LENTITUD"},
    {"index":15,"text":"PENSAMIENTOS DE ACABAR CON SU VIDA"},
    {"index":16,"text":"OÍR VOCES QUE OTRAS PERSONAS NO OYEN"},
    {"index":17,"text":"TEMBLORES"},
    {"index":18,"text":"SENTIR QUE NO SE PUEDE CONFIAR EN LA MAYORÍA DE LAS PERSONAS"},
    {"index":19,"text":"POCO APETITO"},
    {"index":20,"text":"LLANTO FÁCIL"},
    {"index":21,"text":"SENTIRSE INCÓMODO CON PERSONAS DEL SEXO OPUESTO"},
    {"index":22,"text":"SENTIMIENTOS DE ESTAR ATRAPADO O ENCERRADO"},
    {"index":23,"text":"ATAQUES DE MIEDO O PÁNICO"},
    {"index":24,"text":"ESTALLIDOS DE IRA QUE NO PUEDE CONTROLAR"},
    {"index":25,"text":"MIEDO A SALIR SOLO DE CASA"},
    {"index":26,"text":"CULPARSE A SÍ MISMO POR LAS COSAS"},
    {"index":27,"text":"DOLORES EN LA PARTE BAJA DE LA ESPALDA"},
    {"index":28,"text":"SENTIR QUE LAS COSAS SON UNA LUCHA"},
    {"index":29,"text":"SENTIRSE SOLO"},
    {"index":30,"text":"SENTIRSE TRISTE"},
    {"index":31,"text":"PREOCUPARSE DEMASIADO"},
    {"index":32,"text":"FALTA DE INTERÉS POR LAS COSAS"},
    {"index":33,"text":"MIEDO REPENTINO SIN RAZÓN"},
    {"index":34,"text":"SENTIR QUE NO SE LE COMPRENDE"},
    {"index":35,"text":"SENTIR QUE LOS DEMÁS CONOCEN SUS PENSAMIENTOS"},
    {"index":36,"text":"SENTIR QUE LOS DEMÁS NO SON AMISTOSOS"},
    {"index":37,"text":"SENTIR QUE LOS DEMÁS NO LO VALORAN"},
    {"index":38,"text":"TENER QUE HACER LAS COSAS MUY DESPACIO PARA HACERLAS BIEN"},
    {"index":39,"text":"LATIDOS RÁPIDOS DEL CORAZÓN"},
    {"index":40,"text":"NÁUSEAS O MALESTAR ESTOMACAL"},
    {"index":41,"text":"SENTIRSE INFERIOR A LOS DEMÁS"},
    {"index":42,"text":"DOLOR EN LOS MÚSCULOS"},
    {"index":43,"text":"SENTIR QUE LO OBSERVAN O HABLAN DE USTED"},
    {"index":44,"text":"DIFICULTAD PARA DORMIR"},
    {"index":45,"text":"REVISAR LAS COSAS UNA Y OTRA VEZ"},
    {"index":46,"text":"DIFICULTAD PARA TOMAR DECISIONES"},
    {"index":47,"text":"MIEDO A VIAJAR EN AUTOBÚS, TREN O METRO"},
    {"index":48,"text":"PROBLEMAS PARA RESPIRAR"},
    {"index":49,"text":"SOFOCOS O ESCALOFRÍOS"},
    {"index":50,"text":"MIEDO A DESMAYARSE EN PÚBLICO"},
    {"index":51,"text":"PENSAMIENTOS QUE LE AVERGÜENZAN"},
    {"index":52,"text":"HORMIGUEO O ENTUMECIMIENTO EN EL CUERPO"},
    {"index":53,"text":"NÁUSEAS O VÓMITOS"},
    {"index":54,"text":"SENTIR QUE NO TIENE FUTURO"},
    {"index":55,"text":"DIFICULTAD PARA CONCENTRARSE"},
    {"index":56,"text":"SENSACIÓN DE DEBILIDAD EN PARTES DEL CUERPO"},
    {"index":57,"text":"SENTIRSE TENSO O NERVIOSO"},
    {"index":58,"text":"PESADUMBRE EN LOS BRAZOS O PIERNAS"},
    {"index":59,"text":"PENSAR EN LA MUERTE O EN MORIR"},
    {"index":60,"text":"COMER EN EXCESO O POCO APETITO"},
    {"index":61,"text":"SENTIRSE INCÓMODO EN SITUACIONES SOCIALES"},
    {"index":62,"text":"IDEAS EXTRAÑAS O RARAS"},
    {"index":63,"text":"IMPULSOS DE GOLPEAR O HACER DAÑO"},
    {"index":64,"text":"DESPERTARSE MUY TEMPRANO"},
    {"index":65,"text":"REPETIR ACCIONES UNA Y OTRA VEZ"},
    {"index":66,"text":"PROBLEMAS PARA DORMIR PROFUNDAMENTE"},
    {"index":67,"text":"GRITOS O DISCUSIONES FRECUENTES"},
    {"index":68,"text":"SENTIR QUE OTROS NO SON HONESTOS CON USTED"},
    {"index":69,"text":"SENTIRSE INCÓMODO AL COMER O BEBER EN PÚBLICO"},
    {"index":70,"text":"MIEDO A QUEDARSE SOLO"},
    {"index":71,"text":"SENTIR QUE LA VIDA NO VALE LA PENA"},
    {"index":72,"text":"SENTIRSE INQUIETO"},
    {"index":73,"text":"SENTIRSE INCÓMODO EN REUNIONES"},
    {"index":74,"text":"GANAS DE ROMPER COSAS"},
    {"index":75,"text":"MIEDO A SALIR DE CASA"},
    {"index":76,"text":"PENSAR QUE LOS DEMÁS HABLAN MAL DE USTED"},
    {"index":77,"text":"SENTIR QUE SU MENTE NO FUNCIONA BIEN"},
    {"index":78,"text":"SENTIRSE ATERRORIZADO"},
    {"index":79,"text":"SENTIRSE INÚTIL"},
    {"index":80,"text":"SENSACIÓN DE QUE ALGO MALO VA A PASAR"},
    {"index":81,"text":"GRITAR O TIRAR COSAS"},
    {"index":82,"text":"MIEDO A ESTAR ENTRE MUCHA GENTE"},
    {"index":83,"text":"SENTIR QUE LOS DEMÁS SE RÍEN DE USTED"},
    {"index":84,"text":"PENSAMIENTOS EXTRAÑOS QUE NO PUEDE CONTROLAR"},
    {"index":85,"text":"SENTIR QUE NO PUEDE EXPRESAR SUS SENTIMIENTOS"},
    {"index":86,"text":"SENSACIÓN DE FALTA DE AIRE"},
    {"index":87,"text":"IDEAS QUE NO TIENEN SENTIDO"},
    {"index":88,"text":"NO SENTIR CERCANÍA NI INTIMIDAD CON NADIE"},
    {"index":89,"text":"SENTIMIENTO DE CULPA"},
    {"index":90,"text":"LA IDEA DE QUE ALGO ANDA MAL EN SU MENTE"}
  ]'::jsonb,
  '{
    "SOM": {"label": "Somatización", "items": [1,4,12,27,40,42,48,49,52,53,56,58]},
    "OBS": {"label": "Obsesión-Compulsión", "items": [3,9,10,28,38,45,46,51,55,65]},
    "SEN": {"label": "Sensibilidad Interpersonal", "items": [6,21,34,36,37,41,61,69,73]},
    "DEP": {"label": "Depresión", "items": [5,14,15,20,22,26,29,30,31,32,54,71,79]},
    "ANS": {"label": "Ansiedad", "items": [2,17,23,33,39,57,72,78,80,86]},
    "HOS": {"label": "Hostilidad", "items": [11,24,63,67,74,81]},
    "FOB": {"label": "Ansiedad Fóbica", "items": [13,25,47,50,70,75,82]},
    "PAR": {"label": "Ideación Paranoide", "items": [8,18,43,68,76,83]},
    "PSI": {"label": "Psicoticismo", "items": [7,16,35,62,77,84,85,87,88,90]}
  }'::jsonb,
  true
FROM public.assessment_templates
WHERE code = 'SELFCARE_V1'
LIMIT 1;